
project_id = "egiiqbgumgltatfljbcs"

[functions.stock-analysis-proxy]
verify_jwt = false

[auth]
site_url = "https://egiiqbgumgltatfljbcs.supabase.co"
additional_redirect_urls = ["https://lovable.dev", "https://lovable-dev.pages.dev", "https://egiiqbgumgltatfljbcs.lovable.dev"]
